name: Deploy Frontend

on:
  push:
    branches: [ prod ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Stop existing PM2 process if exists
          pm2 stop qp-frontend || true
          
          # Create/Update application directory
          mkdir -p ~/qp/frontend
          
          # Cleanup old deployment excluding .env
          cd ~/qp/frontend
          find . -mindepth 1 ! -name '.env' -delete
          
    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "~/qp/frontend"
        strip_components: 1
        
    - name: Start application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/qp/frontend
          npm ci --production
          npm run build
          pm2 start npm --name qp-frontend -- start
